<?php
namespace tomwof\euler;
include_once __DIR__ . '/../src/Prob002.php';

class Prob002Test extends \PHPUnit_Framework_TestCase
{
    public function testIncrementFibonacci()
    {

        $prob002 = new Prob002(4000001);
        $this->assertEquals(4613732,$prob002->sum);
    }
  }
  // Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
  //
  // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  //
  // By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
