<?php


//echo <<<END
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//</br>
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//</br>
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
//</br>
//END;


//stage one:
//build the fibinachi 

//stage two:
//find the sum of the even values
$stack[0] = 1;
$stack[1] = 2;
$sum = 0;
for($x = 0; $x < 50; $x++)
{
	$a = (count($stack) - 1);
	$b = (count($stack) - 2);
	$stack[$x] =  $stack[$a] + $stack[$b];
	echo "$stack[$x]</br>";
}
echo "===========================================</br>";
foreach ($stack as $value)
{
	if($value % 2 == 0)
	{
		$sum+=$value;
		echo "$sum</br>";
	}
}
echo $sum;
?>
